### ISSUE TITLE
No Default ID.

### ISSUE THREAD

**Issue by WaltDisneyWorld** [jareer12/Bot-o-Maker#1]
When I try to create a bot, I am greeted with:
https://i.ibb.co/VB4dM02/image.png

Please let me know how I can fix this.

**Comment by jareer12** [comment]
will fix soon

**Comment by WaltDisneyWorld** [comment]
Following up.

**Comment by jareer12** [comment]
The problem was in the SQL, the `id` column should b set to `AUTO_INCREMENT`. The issue has been patched and will not occur now.
